### ISSUE TITLE
Scheme reports/forms section: "Scheme Notes"

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-lingo#117]
# preamble

to build out the sections of the scheme forms/reports we will need to:

1. define mappings between form/report fields and the Lingo models
2. implement backend serializers/APIs
3. implement front end UI

# mapping issues

![scheme notes:statement](https://github.com/user-attachments/assets/dfecd806-8379-4779-8e40-7f81a1989cfa)

"Scheme Notes" seem to map onto the "Statement" nodegroup as shown above.  a few questions here:

- should "Statment Metatype" be included here?
- should we be using the non-localized string datatype here (and for similar nodes) as we have a node for defining the language?
- when should the warrant information be shown/gathered?

@Habennin @Philbox @dwuthrich we should discuss & resolve the above questions as they will be blockers to development here. thanks!

**Comment by Philbox** [comment]
@robgaston Statement Metatype is just used to type the Statement Type - eg. Statement Type - Definition, Statement Metatype - Statement (or Note - however @Habennin has defined the collection for that node)

In other words the metatype is just saying 'The node 'Statement Type' holds a value which is of type 'Note'. Metatype = 'type of type'

I'm not sure about the 'String' datatype part of your question but suspect the answer may be 'Yes'...?

The warrant should be collected when the note is added.

**Comment by Habennin** [comment]
So there is a bit of a conflict in the UI represnetaiotn about what is happening here. Is this a general field for making 'notes' or 'statements' about the scheme as is implied by the label and which would mean it is multi value and you would gather all kinds of statements or is this only for inputting the description of the scheme itself and nothing else.

As usual the whole node and its children was foreseen to be used. So the actual note goes in statement_content, the type goes in statement_type. If the only function of this is to record the description then this type should be set to 'scope note'.

The field group has a field statement_language which is the place where it is foreseen that they would pick the language in which they had written the description.

And then yes there is a subnode for the warrant stuff so one would want to collect at least who described it (@Philbox might say even more data than that?) and this is in the subnode for the warrant and in the field called:statement_data_assignment_actor.

Actually I had setup the cards so they would show the stuff that should be collected for those nodes in one view. Maybe it could be used as a pattern?

**Comment by robgaston** [comment]
Sounds like we should actually show all fields from the nodegroup in this form, is that correct?

@dwuthrich would it be okay for us to simply collect warrant information inside this form, or should we be doing something else to collect that?

**Comment by robgaston** [comment]
We should hide the warrant fields in the form/report currently.  These may be removed for the Scheme model in the future.  "Metatype" should be auto-populated w/ a default value (which still need to be restored from the RDM-CLM migration).

@chrabyrd we should be able to start work on this section w/ this information.

**Comment by Habennin** [comment]
So does that mean that the user is only able to add the scope note and not making any other notes?

@Philbox is is true that the warrant is not needed on this model?

**Comment by robgaston** [comment]
It would be fine to show the metatype, this was just my understanding from our conversations.  Please set me straight!

**Comment by Philbox** [comment]
@robgaston Each scheme can have many notes eg. a History Note, Definition or Scope Note.
Each note in turn can have a warrant - the reason why something is defined as such or the reason something is added to the history.

So I think warrant is needed here and needs to be editable. It makes sense to me that the warrant nodes be included in the Scheme Notes UI

**Comment by robgaston** [comment]
Okay, then it sounds like we should show the entire card here, is that correct @Philbox @Habennin?

**Comment by Philbox** [comment]
It's a yes from me 
@Habennin over to you.
