### ISSUE TITLE
Scheme reports/forms section: "Scheme URIs"

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-lingo#118]
# preamble

to build out the sections of the scheme forms/reports we will need to:

1. define mappings between form/report fields and the Lingo models
2. implement backend serializers/APIs
3. implement front end UI

# mapping issues

![scheme uris:identifiers](https://github.com/user-attachments/assets/439eb34b-5691-43a8-a546-c752bc14b39e)
![scheme uris:namespace](https://github.com/user-attachments/assets/cdf09c35-04ca-4b03-9615-70cbccb39962)

some questions:

- "Scheme URIs" appears to come from the Identifiers nodegroup.  is this correct? 
- is the "Namespace" nodegroup involved at all here?  if not, how is that used?
- Should URIs actually be manually editable or should they be autogenerated on publish based on a function?

@Habennin @Philbox @dwuthrich we should discuss & resolve the above questions as they will be blockers to development here. thanks!

**Comment by Philbox** [comment]
@robgaston My understanding is that when you create a scheme you create the namespace and that becomes the root of the URI.
So for example https://heritagedata.org/live/schemes/560 is the namespace for the FISH Archaeological Sciences Thesaurus (it is also represented by http://purl.org/heritagedata/schemes/560).

Any concept, eg. 'Investigative Techniques' added to that scheme is then assigned an identifier. In this case - 142153 

The pattern is [Namespace]+"/Concepts/"+[Identifier] = persistent URI 

Thus, in this example giving https://heritagedata.org/live/schemes/560/concepts/142153 (and its purl.org equivalent http://purl.org/heritagedata/schemes/560/concepts/142153)

**Comment by Philbox** [comment]
Just realized that I've missed a step. the identifier for the above scheme is '560' and the URI is {Namespace]+"/schemes/"+[Identifier] where namespace = https://heritagedata.org/live/ or http://purl.org/heritagedata

**Comment by Philbox** [comment]
In essence for all HE vocabs the namespace will be the same

**Comment by Habennin** [comment]
So the space for holding the base namespace information was modelled in the node called namespace_name.

It's intention was to hold the route of the namespace (and it assumes there is only one). 

There is nothing presently in there to independtly put in a slug that you fit somewhere in the uri string.

So as it is presently I would expect that the value the user should fill in here is:

https://heritagedata.org/live/schemes/560/concepts/](https://heritagedata.org/live/schemes/560/concepts/

And then there is some function which creates an autoupdate number somewhere on the new concept created that assigns it the next free number.

Now for the user scenario where you want each object to have two URIs I suppose you could put in two base namespaces.

http://purl.org/heritagedata/schemes/560/concepts/

and ask the system to generate two for the concept.

If you wanted to further complexify things I suppose one could expand the function of this node group and store both basenames and slug names and then have something to create the formula of things that Phil describes above.

I kind of wonder though if this isn't something that wouldn't even be like a function that should be setup at the model level?

**Comment by robgaston** [comment]
@Philbox @Habennin so then should we just allow the user to populate the namespace for the scheme and autogenerate the URI based on that when the scheme is published?

**Comment by robgaston** [comment]
@chrabyrd This section should become "Scheme Namespace".  It is cardinality 1, and we should just show the node for "namespace name".  we should be unblocked on working on this section now
