### ISSUE TITLE
Scheme reports/forms section: "Trusted Authorities"

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-lingo#119]
# preamble

to build out the sections of the scheme forms/reports we will need to:

1. define mappings between form/report fields and the Lingo models
2. implement backend serializers/APIs
3. implement front end UI

# mapping issues

it's unclear where in the Scheme model these data are stored. Is it possibly related to "Standards" or "Conventions"?:

![scheme authorities:sources](https://github.com/user-attachments/assets/62fd63d0-3b33-4cce-9f48-04d761daafee)

@Habennin @Philbox @dwuthrich we should discuss & resolve the above questions as they will be blockers to development here. thanks!

**Comment by Philbox** [comment]
@robgaston I don't think this is reflected in the modelling at all. Is this similar to the Thesaurus Service Provider in the Systems Settings in Core Arches? How is that handled in the original RDM modelling?

![image](https://github.com/user-attachments/assets/8b7ba447-f1ed-423a-b02e-0444b00d587b)

**Comment by Habennin** [comment]
I agree with @Philbox , this wasn't modelled and I don't remember the conversation if we had it. 

What are we looking to document here? I can add modelling for it if we need it and it is important.

So it's an endpoint for this thesaurus? For other thesauri?

**Comment by robgaston** [comment]
It would seem that this is not supported in the models or in the application, so i’m assuming we can remove this entirely.  thoughts, @dwuthrich?

**Comment by robgaston** [comment]
this can be removed entirely -- should be handled via system settings as we do w/ the current RDM.

**Comment by robgaston** [comment]
this can be removed entirely -- should be handled via system settings as we do w/ the current RDM.

**Comment by Habennin** [comment]
from a user simplicity point of view, it might be nice to handle it in the data and not in an obscure place in django but whatever is best.

**Comment by robgaston** [comment]
@Habennin the actual value that we are managing here is not simply a URL (or other easily understandable value), but rather a namespace for a Python module that must be developed to integrate with a data source.  Therefore, it seems quite technical and likely a better fit for a system administrator or developer with server access to control.
