### ISSUE TITLE
Scheme reports/forms section: "Standards Followed"

### ISSUE THREAD

**Issue by robgaston** [archesproject/arches-lingo#120]
# preamble

to build out the sections of the scheme forms/reports we will need to:

1. define mappings between form/report fields and the Lingo models
2. implement backend serializers/APIs
3. implement front end UI

# mapping issues

![scheme standards](https://github.com/user-attachments/assets/8c5e454d-69ec-4521-b13b-0757293adec2)

This seems to refer to "Standards/Sources" in the Scheme model, but the mockup depicts two string fields where this is actually a resource-instance-list datatype node.  So which is correct?

@Habennin @Philbox @dwuthrich we should discuss & resolve the above questions as they will be blockers to development here. thanks!

**Comment by Philbox** [comment]
@robgaston yes the Standards relates to a resource instance of a bibliographic source such as 'BS8723 - Guidelines for the creation of monolingual thesauri'. I'm not sure what the Version field does here. It may not be necessary.

**Comment by robgaston** [comment]
this makes sense, sounds like we can just use the “Standards/Sources” field here.

one question that occurs to me: we had previously said that these source instances would be created in Core arches, not in Lingo. is the assumption then that they have already been created by lingo users, or should we somehow link out to core arches for users who need to assign source records that haven’t been entered into the system?

**Comment by robgaston** [comment]
@chrabyrd "Scheme Standards" should just be the "Sources/Standards" node as depicted above, which is a cardinality 1 `resource-instance-list` node.  We can start by just building the UI to assign those relationships, but we will also need to build a quick (modal as we do in Arches?) UI for adding a new Textual Work resource instance via Lingo.  this can be a separate ticket/work item from the basic form itself, and I note that we will reuse this in multiple places as we build out the Concept forms.

**Comment by Habennin** [comment]
In reference to:

"one question that occurs to me: we had previously said that these source instances would be created in Core arches, not in Lingo. is the assumption then that they have already been created by lingo users, or should we somehow link out to core arches for users who need to assign source records that haven’t been entered into the system?"

Don't know if this a question to me, but it seems to me that one needs a form for entering data for each of the entities in the model. Just like in normal Arches if the form points out to another model, one will have to be able to either refer to a preexisting entity or open a form to create and document a new entity.
