### ISSUE TITLE
Create a side navigation bar

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-lingo#14]
This should exist outside of the Vue router. For this iteration it should only have basic styling, and reflect which page the user on via icon highlight or button pressed state -- depending on implementation.

It should contain links for:
- User homepage
- Search page
- Scheme list page

It should be responsive, and support becoming a topnav or integrating into the current topnav on mobile devices.

**Comment by jacobtylerwalls** [comment]
@chrabyrd is there a mockup?

**Comment by chrabyrd** [comment]
resolved in #62
