### ISSUE TITLE
Application does not retain user logged-in status

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-lingo#56]
To reproduce:

1. visit the root site ( eg localhost:8000/ )
2. login
3. refresh the page
4. notice that instead of the page the user is redirected to after login, the login form is displayed

**Comment by jacobtylerwalls** [comment]
Thanks for finding, I must have broken this after adding the unauthorized user redirect.

**Comment by chrabyrd** [comment]
resolved in #64
